In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

df = pd.read_csv('rain.csv')

In [ ]:
df

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,ANDAMAN & NICOBAR ISLANDS,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,ANDAMAN & NICOBAR ISLANDS,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,ANDAMAN & NICOBAR ISLANDS,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,ANDAMAN & NICOBAR ISLANDS,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4111,LAKSHADWEEP,2011,5.1,2.8,3.1,85.9,107.2,153.6,350.2,254.0,255.2,117.4,184.3,14.9,1533.7,7.9,196.2,1013.0,316.6
4112,LAKSHADWEEP,2012,19.2,0.1,1.6,76.8,21.2,327.0,231.5,381.2,179.8,145.9,12.4,8.8,1405.5,19.3,99.6,1119.5,167.1
4113,LAKSHADWEEP,2013,26.2,34.4,37.5,5.3,88.3,426.2,296.4,154.4,180.0,72.8,78.1,26.7,1426.3,60.6,131.1,1057.0,177.6
4114,LAKSHADWEEP,2014,53.2,16.1,4.4,14.9,57.4,244.1,116.1,466.1,132.2,169.2,59.0,62.3,1395.0,69.3,76.7,958.5,290.5
4115,LAKSHADWEEP,2015,2.2,0.5,3.7,87.1,133.1,296.6,257.5,146.4,160.4,165.4,231.0,159.0,1642.9,2.7,223.9,860.9,555.4

In [ ]:
df.shape

(4116, 19)

In [ ]:
df.shape[0]

4116

In [ ]:
df.dtypes

SUBDIVISION     object
YEAR             int64
JAN            float64
FEB            float64
MAR            float64
APR            float64
MAY            float64
JUN            float64
JUL            float64
AUG            float64
SEP            float64
OCT            float64
NOV            float64
DEC            float64
ANNUAL         float64
Jan-Feb        float64
Mar-May        float64
Jun-Sep        float64
Oct-Dec        float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SUBDIVISION  4116 non-null   object
 1   YEAR         4116 non-null   int64
 2   JAN          4112 non-null   float64
 3   FEB          4113 non-null   float64
 4   MAR          4110 non-null   float64
 5   APR          4112 non-null   float64
 6   MAY          4113 non-null   float64
 7   JUN          4111 non-null   float64
 8   JUL          4109 non-null   float64
 9   AUG          4112 non-null   float64
 10  SEP          4110 non-null   float64
 11  OCT          4109 non-null   float64
 12  NOV          4105 non-null   float64
 13  DEC          4106 non-null   float64
 14  ANNUAL       4090 non-null   float64
 15  Jan-Feb      4110 non-null   float64
 16  Mar-May      4107 non-null   float64
 17  Jun-Sep      4106 non-null   float64
 18  Oct-Dec      4103 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 611.1+ KB

In [ ]:
df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,ANDAMAN & NICOBAR ISLANDS,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,ANDAMAN & NICOBAR ISLANDS,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,ANDAMAN & NICOBAR ISLANDS,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,ANDAMAN & NICOBAR ISLANDS,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [ ]:
df.describe()

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
count,4116.000000,4112.000000,4113.000000,4110.000000,4112.000000,4113.000000,4111.000000,4109.000000,4112.000000,4110.000000,4109.000000,4105.000000,4106.000000,4090.000000,4110.000000,4107.000000,4106.000000,4103.000000
mean,1958.218659,18.957320,21.805325,27.359197,43.127432,85.745417,230.234444,347.214334,290.263497,197.361922,95.507009,39.866163,18.870580,1411.008900,40.747786,155.901753,1064.724769,154.100487
std,33.140898,33.585371,35.909488,46.959424,67.831168,123.234904,234.710758,269.539667,188.770477,135.408345,99.519134,68.685410,42.369611,903.846565,59.308277,201.316965,707.741531,166.942660
min,1901.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.400000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,62.300000,0.000000,0.000000,57.400000,0.000000
25%,1930.000000,0.600000,0.600000,1.000000,3.000000,8.600000,70.350000,175.600000,155.975000,100.525000,14.600000,0.700000,0.100000,804.500000,4.100000,24.050000,573.850000,34.200000
50%,1958.000000,6.000000,6.700000,7.800000,15.700000,36.600000,138.700000,284.800000,259.400000,173.900000,65.200000,9.500000,3.000000,1121.300000,19.200000,74.800000,881.100000,98.200000
75%,1987.000000,22.200000,26.800000,31.300000,49.950000,97.200000,305.150000,418.400000,377.800000,265.800000,148.400000,46.100000,17.500000,1644.775000,50.375000,196.950000,1288.175000,213.500000
max,2015.000000,583.700000,403.500000,605.600000,595.100000,1168.600000,1609.900000,2362.800000,1664.600000,1222.000000,948.300000,648.900000,617.500000,6331.100000,699.500000,1745.800000,4536.900000,1252.500000

In [ ]:
df.tail()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
4111,LAKSHADWEEP,2011,5.1,2.8,3.1,85.9,107.2,153.6,350.2,254.0,255.2,117.4,184.3,14.9,1533.7,7.9,196.2,1013.0,316.6
4112,LAKSHADWEEP,2012,19.2,0.1,1.6,76.8,21.2,327.0,231.5,381.2,179.8,145.9,12.4,8.8,1405.5,19.3,99.6,1119.5,167.1
4113,LAKSHADWEEP,2013,26.2,34.4,37.5,5.3,88.3,426.2,296.4,154.4,180.0,72.8,78.1,26.7,1426.3,60.6,131.1,1057.0,177.6
4114,LAKSHADWEEP,2014,53.2,16.1,4.4,14.9,57.4,244.1,116.1,466.1,132.2,169.2,59.0,62.3,1395.0,69.3,76.7,958.5,290.5
4115,LAKSHADWEEP,2015,2.2,0.5,3.7,87.1,133.1,296.6,257.5,146.4,160.4,165.4,231.0,159.0,1642.9,2.7,223.9,860.9,555.4

In [ ]:
df.tail(1)

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
4115,LAKSHADWEEP,2015,2.2,0.5,3.7,87.1,133.1,296.6,257.5,146.4,160.4,165.4,231.0,159.0,1642.9,2.7,223.9,860.9,555.4

In [ ]:
df_filled=df.fillna(0)

print(df_filled.isnull().sum())
for column in df.columns:
    if df[column].dtype == 'object':
        df[column].fillna(df[column].mode()[0], inplace=True)
    else:
        df[column].fillna(df[column].mean(), inplace=True)

SUBDIVISION    0
YEAR           0
JAN            0
FEB            0
MAR            0
APR            0
MAY            0
JUN            0
JUL            0
AUG            0
SEP            0
OCT            0
NOV            0
DEC            0
ANNUAL         0
Jan-Feb        0
Mar-May        0
Jun-Sep        0
Oct-Dec        0
dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
# Select columns for standardization (excluding 'SUBDIVISION' and 'YEAR')
rainfall_columns = df.columns[2:]
 # Apply standardization
scaler = StandardScaler()
df[rainfall_columns] = scaler.fit_transform(df[rainfall_columns])
df

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,0.901019,1.819197,0.039233,-0.602264,3.596952,1.224806,0.066421,1.011559,0.999593,2.946952,7.557516,0.348107,2.178089,1.612483,2.011209,0.893576,4.957440
1,ANDAMAN & NICOBAR ISLANDS,1902,-0.564795,3.844716,-0.323090,-0.636192,2.925549,1.308374,-0.439377,2.456519,3.465350,1.022838,4.653100,3.347188,2.341819,2.009055,1.503928,1.586280,3.375762
2,ANDAMAN & NICOBAR ISLANDS,1903,-0.186424,3.404507,-0.583110,-0.621441,1.212540,1.064492,1.415586,0.193137,1.046898,0.861909,3.565402,4.871544,1.716539,1.956741,0.398853,1.144993,3.219155
3,ANDAMAN & NICOBAR ISLANDS,1904,-0.284741,-0.197964,-0.583110,2.349501,1.775966,1.129300,0.574818,-0.689952,4.605097,1.274291,3.919706,0.501724,1.852185,-0.280938,1.745632,1.291570,2.501520
4,ANDAMAN & NICOBAR ISLANDS,1905,-0.526064,-0.607525,-0.512776,-0.239378,1.573002,1.698926,0.079790,0.213280,0.736461,1.661527,-0.210922,7.700464,1.282851,-0.665698,0.764890,0.792557,2.860337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4111,LAKSHADWEEP,2011,-0.412851,-0.529514,-0.517039,0.630957,0.174180,-0.326744,0.011088,-0.192220,0.427502,0.220202,2.105903,-0.093838,0.136191,-0.554320,0.200417,-0.073182,0.975045
4112,LAKSHADWEEP,2012,0.007230,-0.604739,-0.549009,0.496719,-0.524014,0.412577,-0.429721,0.482023,-0.129806,0.506858,-0.400468,-0.238002,-0.006115,-0.361940,-0.280008,0.077498,0.078001
4113,LAKSHADWEEP,2013,0.215781,0.350904,0.216132,-0.558009,0.020739,0.835533,-0.188706,-0.720166,-0.128328,-0.228389,0.557465,0.185036,0.016974,0.335014,-0.123347,-0.010929,0.141004
4114,LAKSHADWEEP,2014,1.020191,-0.158958,-0.489332,-0.416395,-0.230123,0.059118,-0.858275,0.932049,-0.481635,0.741211,0.278979,1.026386,-0.017770,0.481830,-0.393897,-0.150291,0.818437
4115,LAKSHADWEEP,2015,-0.499250,-0.593595,-0.504251,0.648659,0.384450,0.282961,-0.333167,-0.762571,-0.273199,0.702991,2.786808,3.311738,0.257406,-0.642072,0.338178,-0.288379,2.407915

In [ ]:
from sklearn.preprocessing import MinMaxScaler
# Apply normalization (to range [0,1])
normalizer = MinMaxScaler()
df[rainfall_columns] = normalizer.fit_transform(df[rainfall_columns])
df

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,0.084290,0.215861,0.048217,0.003865,0.452507,0.321280,0.154520,0.289018,0.272117,0.409680,0.860225,0.054413,0.528155,0.194853,0.320942,0.365867,0.782675
1,ANDAMAN & NICOBAR ISLANDS,1902,0.000000,0.396035,0.020145,0.000000,0.381739,0.333458,0.096877,0.452781,0.545135,0.207951,0.553244,0.259919,0.551685,0.228449,0.262516,0.475165,0.572216
2,ANDAMAN & NICOBAR ISLANDS,1903,0.021758,0.356877,0.000000,0.001680,0.201181,0.297919,0.308278,0.196263,0.277355,0.191079,0.438280,0.364372,0.461827,0.224017,0.135239,0.405536,0.551377
3,ANDAMAN & NICOBAR ISLANDS,1904,0.016104,0.036431,0.000000,0.340111,0.260568,0.307363,0.212460,0.096179,0.671332,0.234314,0.475728,0.064939,0.481320,0.034453,0.290354,0.428664,0.455888
4,ANDAMAN & NICOBAR ISLANDS,1905,0.002227,0.000000,0.005449,0.045202,0.239175,0.390370,0.156044,0.198546,0.242982,0.274913,0.039143,0.558219,0.399502,0.001858,0.177397,0.349927,0.503633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4111,LAKSHADWEEP,2011,0.008737,0.006939,0.005119,0.144345,0.091734,0.095185,0.148214,0.152589,0.208773,0.123800,0.284019,0.024130,0.234718,0.011294,0.112384,0.213327,0.252774
4112,LAKSHADWEEP,2012,0.032894,0.000248,0.002642,0.129054,0.018141,0.202920,0.097977,0.229004,0.147066,0.153854,0.019109,0.014251,0.214267,0.027591,0.057051,0.237102,0.133413
4113,LAKSHADWEEP,2013,0.044886,0.085254,0.061922,0.008906,0.075560,0.264554,0.125444,0.092755,0.147230,0.076769,0.120358,0.043239,0.217586,0.086633,0.075095,0.223150,0.141796
4114,LAKSHADWEEP,2014,0.091143,0.039901,0.007266,0.025038,0.049119,0.151413,0.049137,0.280007,0.108110,0.178425,0.090923,0.100891,0.212593,0.099071,0.043934,0.201161,0.231936
4115,LAKSHADWEEP,2015,0.003769,0.001239,0.006110,0.146362,0.113897,0.184032,0.108981,0.087949,0.131189,0.174417,0.355987,0.257490,0.252138,0.003860,0.128251,0.179373,0.443433

In [ ]:
import numpy as np
# Log transformation (adding 1 to avoid log(0))
df[rainfall_columns] = np.log1p(df[rainfall_columns])
df

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,0.080925,0.195453,0.047090,0.003857,0.373291,0.278601,0.143685,0.253881,0.240683,0.343363,0.620697,0.052984,0.424061,0.178024,0.278345,0.311789,0.578115
1,ANDAMAN & NICOBAR ISLANDS,1902,0.000000,0.333636,0.019945,0.000000,0.323343,0.287775,0.092467,0.373480,0.435111,0.188926,0.440346,0.231047,0.439341,0.205752,0.233106,0.388770,0.452486
2,ANDAMAN & NICOBAR ISLANDS,1903,0.021524,0.305186,0.000000,0.001679,0.183305,0.260762,0.268712,0.179203,0.244791,0.174859,0.363448,0.310695,0.379687,0.202138,0.126843,0.340419,0.439143
3,ANDAMAN & NICOBAR ISLANDS,1904,0.015976,0.035783,0.000000,0.292752,0.231563,0.268012,0.192651,0.091831,0.513621,0.210515,0.389152,0.062918,0.392934,0.033873,0.254917,0.356740,0.375616
4,ANDAMAN & NICOBAR ISLANDS,1905,0.002225,0.000000,0.005434,0.044211,0.214446,0.329570,0.145004,0.181109,0.217514,0.242878,0.038396,0.443543,0.336117,0.001857,0.163306,0.300051,0.407884
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4111,LAKSHADWEEP,2011,0.008699,0.006915,0.005106,0.134833,0.087767,0.090923,0.138208,0.142011,0.189606,0.116716,0.249995,0.023843,0.210843,0.011230,0.106505,0.193366,0.225361
4112,LAKSHADWEEP,2012,0.032364,0.000248,0.002639,0.121380,0.017979,0.184752,0.093469,0.206204,0.137207,0.143108,0.018929,0.014150,0.194141,0.027217,0.055483,0.212772,0.125234
4113,LAKSHADWEEP,2013,0.043908,0.081814,0.060081,0.008867,0.072842,0.234720,0.118178,0.088702,0.137350,0.073965,0.113648,0.042330,0.196870,0.083084,0.072409,0.201429,0.132603
4114,LAKSHADWEEP,2014,0.087226,0.039125,0.007239,0.024729,0.047950,0.140990,0.047968,0.246866,0.102656,0.164178,0.087024,0.096120,0.192761,0.094465,0.042996,0.183288,0.208587
4115,LAKSHADWEEP,2015,0.003762,0.001238,0.006091,0.136593,0.107865,0.168926,0.103441,0.084294,0.123269,0.160772,0.304530,0.229118,0.224852,0.003852,0.120668,0.164983,0.367024

In [ ]:
# Aggregating the data by 'SUBDIVISION' and 'YEAR' (calculating the mean for each group)
rain_aggregated = df.groupby(['SUBDIVISION','YEAR']).mean().reset_index()
rain_aggregated

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,0.080925,0.195453,0.047090,0.003857,0.373291,0.278601,0.143685,0.253881,0.240683,0.343363,0.620697,0.052984,0.424061,0.178024,0.278345,0.311789,0.578115
1,ANDAMAN & NICOBAR ISLANDS,1902,0.000000,0.333636,0.019945,0.000000,0.323343,0.287775,0.092467,0.373480,0.435111,0.188926,0.440346,0.231047,0.439341,0.205752,0.233106,0.388770,0.452486
2,ANDAMAN & NICOBAR ISLANDS,1903,0.021524,0.305186,0.000000,0.001679,0.183305,0.260762,0.268712,0.179203,0.244791,0.174859,0.363448,0.310695,0.379687,0.202138,0.126843,0.340419,0.439143
3,ANDAMAN & NICOBAR ISLANDS,1904,0.015976,0.035783,0.000000,0.292752,0.231563,0.268012,0.192651,0.091831,0.513621,0.210515,0.389152,0.062918,0.392934,0.033873,0.254917,0.356740,0.375616
4,ANDAMAN & NICOBAR ISLANDS,1905,0.002225,0.000000,0.005434,0.044211,0.214446,0.329570,0.145004,0.181109,0.217514,0.242878,0.038396,0.443543,0.336117,0.001857,0.163306,0.300051,0.407884
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4111,WEST UTTAR PRADESH,2011,0.003591,0.025448,0.006419,0.004694,0.025014,0.103495,0.087438,0.130636,0.079873,0.000738,0.000770,0.002426,0.108023,0.017712,0.020580,0.139097,0.002153
4112,WEST UTTAR PRADESH,2012,0.024538,0.000248,0.002309,0.007867,0.000257,0.002234,0.059598,0.085784,0.053925,0.000527,0.000154,0.003234,0.050894,0.020517,0.003659,0.066622,0.002153
4113,WEST UTTAR PRADESH,2013,0.034353,0.158919,0.005763,0.002685,0.001795,0.111696,0.094394,0.159116,0.041755,0.062540,0.002616,0.014310,0.130030,0.120907,0.004116,0.146432,0.055742
4114,WEST UTTAR PRADESH,2014,0.079502,0.070330,0.036639,0.008867,0.009369,0.013331,0.062187,0.047513,0.066945,0.015279,0.000000,0.026054,0.065537,0.105332,0.022093,0.061051,0.024293
4115,WEST UTTAR PRADESH,2015,0.052723,0.017687,0.104634,0.034680,0.006907,0.043525,0.078987,0.082692,0.021376,0.007250,0.003077,0.004847,0.079748,0.053984,0.053476,0.081157,0.009456

In [ ]:
# Discretizing the 'ANNUAL' rainfall into three categories: low, medium, and high
df['rainfall_category'] = pd.cut(df['ANNUAL'], bins=[-np.inf, 0.33, 0.66, np.inf], labels=["low", "medium", "high"])
df

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec,rainfall_category
0,ANDAMAN & NICOBAR ISLANDS,1901,0.080925,0.195453,0.047090,0.003857,0.373291,0.278601,0.143685,0.253881,0.240683,0.343363,0.620697,0.052984,0.424061,0.178024,0.278345,0.311789,0.578115,medium
1,ANDAMAN & NICOBAR ISLANDS,1902,0.000000,0.333636,0.019945,0.000000,0.323343,0.287775,0.092467,0.373480,0.435111,0.188926,0.440346,0.231047,0.439341,0.205752,0.233106,0.388770,0.452486,medium
2,ANDAMAN & NICOBAR ISLANDS,1903,0.021524,0.305186,0.000000,0.001679,0.183305,0.260762,0.268712,0.179203,0.244791,0.174859,0.363448,0.310695,0.379687,0.202138,0.126843,0.340419,0.439143,medium
3,ANDAMAN & NICOBAR ISLANDS,1904,0.015976,0.035783,0.000000,0.292752,0.231563,0.268012,0.192651,0.091831,0.513621,0.210515,0.389152,0.062918,0.392934,0.033873,0.254917,0.356740,0.375616,medium
4,ANDAMAN & NICOBAR ISLANDS,1905,0.002225,0.000000,0.005434,0.044211,0.214446,0.329570,0.145004,0.181109,0.217514,0.242878,0.038396,0.443543,0.336117,0.001857,0.163306,0.300051,0.407884,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4111,LAKSHADWEEP,2011,0.008699,0.006915,0.005106,0.134833,0.087767,0.090923,0.138208,0.142011,0.189606,0.116716,0.249995,0.023843,0.210843,0.011230,0.106505,0.193366,0.225361,low
4112,LAKSHADWEEP,2012,0.032364,0.000248,0.002639,0.121380,0.017979,0.184752,0.093469,0.206204,0.137207,0.143108,0.018929,0.014150,0.194141,0.027217,0.055483,0.212772,0.125234,low
4113,LAKSHADWEEP,2013,0.043908,0.081814,0.060081,0.008867,0.072842,0.234720,0.118178,0.088702,0.137350,0.073965,0.113648,0.042330,0.196870,0.083084,0.072409,0.201429,0.132603,low
4114,LAKSHADWEEP,2014,0.087226,0.039125,0.007239,0.024729,0.047950,0.140990,0.047968,0.246866,0.102656,0.164178,0.087024,0.096120,0.192761,0.094465,0.042996,0.183288,0.208587,low
4115,LAKSHADWEEP,2015,0.003762,0.001238,0.006091,0.136593,0.107865,0.168926,0.103441,0.084294,0.123269,0.160772,0.304530,0.229118,0.224852,0.003852,0.120668,0.164983,0.367024,low

In [ ]:
df.to_csv('rain_processed.csv', index=False)